In [1]:
pwd

'C:\\Users\\shoaibakhtar'

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('tmdb-movies.csv')

In [4]:
df

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/15,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/15,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/15,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/15,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/15,2947,7.3,2015,1.747999e+08,1.385749e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10861,21,tt0060371,0.080598,0,0,The Endless Summer,Michael Hynson|Robert August|Lord 'Tally Ho' B...,NaN,Bruce Brown,NaN,...,"The Endless Summer, by Bruce Brown, is one of ...",95,Documentary,Bruce Brown Films,6/15/66,11,7.4,1966,0.000000e+00,0.000000e+00
10862,20379,tt0060472,0.065543,0,0,Grand Prix,James Garner|Eva Marie Saint|Yves Montand|Tosh...,NaN,John Frankenheimer,Cinerama sweeps YOU into a drama of speed and ...,...,Grand Prix driver Pete Aron is fired by his te...,176,Action|Adventure|Drama,Cherokee Productions|Joel Productions|Douglas ...,12/21/66,20,5.7,1966,0.000000e+00,0.000000e+00
10863,39768,tt0060161,0.065141,0,0,Beregis Avtomobilya,Innokentiy Smoktunovskiy|Oleg Efremov|Georgi Z...,NaN,Eldar Ryazanov,NaN,...,An insurance agent who moonlights as a carthie...,94,Mystery|Comedy,Mosfilm,1/1/66,11,6.5,1966,0.000000e+00,0.000000e+00
10864,21449,tt0061177,0.064317,0,0,"What's Up, Tiger Lily?",Tatsuya Mihashi|Akiko Wakabayashi|Mie Hama|Joh...,NaN,Woody Allen,WOODY ALLEN STRIKES BACK!,...,"In comic Woody Allen's film debut, he took the...",80,Action|Comedy,Benedict Pictures Corp.,11/2/66,22,5.4,1966,0.000000e+00,0.000000e+00
10865,22293,tt0060666,0.035919,19000,0,Manos: The Hands of Fate,Harold P. Warren|Tom Neyman|John Reynolds|Dian...,NaN,Harold P. Warren,It's Shocking! It's Beyond Your Imagination!,...,A family gets lost on the road and stumbles up...,74,Horror,Norm-Iris,11/15/66,15,1.5,1966,1.276423e+05,0.000000e+00

In [5]:
df.columns

Index(['id', 'imdb_id', 'popularity', 'budget', 'revenue', 'original_title',
       'cast', 'homepage', 'director', 'tagline', 'keywords', 'overview',
       'runtime', 'genres', 'production_companies', 'release_date',
       'vote_count', 'vote_average', 'release_year', 'budget_adj',
       'revenue_adj'],
      dtype='object')

movie with highest budget

In [11]:
df[df['budget']==df['budget'].max()][['original_title','budget']]

         original_title     budget
2244  The Warrior's Way  425000000

movies with third highest and 3rd lowest budget

In [20]:
#3rd highest
df[df['budget']== df['budget'].nlargest(3).iloc[-1]][['original_title','budget']]

                                original_title     budget
7387  Pirates of the Caribbean: At World's End  300000000

In [29]:
#3rd lowest

df[df['budget']== df['budget'].nsmallest(3).iloc[-1]][['original_title','budget']].head(1)

   original_title  budget
30     Mr. Holmes       0

In [36]:
df1=df.loc[(df['budget']!=0)]

In [37]:
df1

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/15,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/15,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/15,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/15,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/15,2947,7.3,2015,1.747999e+08,1.385749e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10835,5923,tt0060934,0.299911,12000000,20000000,The Sand Pebbles,Steve McQueen|Richard Attenborough|Richard Cre...,NaN,Robert Wise,This is the heroic story of the men on the U.S...,...,Engineer Jake Holman arrives aboard the gunboa...,182,Action|Adventure|Drama|War|Romance,Twentieth Century Fox Film Corporation|Solar P...,12/20/66,28,7.0,1966,8.061618e+07,1.343603e+08
10841,42701,tt0062262,0.264925,75000,0,The Shooting,Will Hutchins|Millie Perkins|Jack Nicholson|Wa...,NaN,Monte Hellman,"Suspenseful desert pursuit in the ""High Noon"" ...",...,A hired gun seeks to enact revenge on a group ...,82,Western,Proteus Films,10/23/66,12,5.5,1966,5.038511e+05,0.000000e+00
10848,2161,tt0060397,0.207257,5115000,12000000,Fantastic Voyage,Stephen Boyd|Raquel Welch|Edmond O'Brien|Donal...,NaN,Richard Fleischer,A Fantastic and Spectacular Voyage... Through ...,...,The science of miniaturization has been unlock...,100,Adventure|Science Fiction,Twentieth Century Fox Film Corporation,8/24/66,42,6.7,1966,3.436265e+07,8.061618e+07
10855,13343,tt0059221,0.141026,700000,0,The Ghost & Mr. Chicken,Don Knotts|Joan Staley|Liam Redmond|Dick Sarge...,NaN,Alan Rafkin,G-G-GUARANTEED! YOU'LL BE SCARED UNTIL YOU LAU...,...,Luther Heggs aspires to being a reporter for h...,90,Comedy|Family|Mystery|Romance,Universal Pictures,1/20/66,14,6.1,1966,4.702610e+06,0.000000e+00
10865,22293,tt0060666,0.035919,19000,0,Manos: The Hands of Fate,Harold P. Warren|Tom Neyman|John Reynolds|Dian...,NaN,Harold P. Warren,It's Shocking! It's Beyond Your Imagination!,...,A family gets lost on the road and stumbles up...,74,Horror,Norm-Iris,11/15/66,15,1.5,1966,1.276423e+05,0.000000e+00

In [43]:
#3rd smallest droppin all zero values from budget
df1[df1['budget']== df1['budget'].nsmallest(3).iloc[-1]][['original_title','budget']].head(1)

     original_title  budget
1151    Fear Clinic       1

In [44]:
df.columns

Index(['id', 'imdb_id', 'popularity', 'budget', 'revenue', 'original_title',
       'cast', 'homepage', 'director', 'tagline', 'keywords', 'overview',
       'runtime', 'genres', 'production_companies', 'release_date',
       'vote_count', 'vote_average', 'release_year', 'budget_adj',
       'revenue_adj'],
      dtype='object')

average number of words in movie title between 2000 and 2005

In [56]:
str1=''
n=len(df['original_title'])
for i in df['original_title']:
    str1=str1+i.replace(' ','')
avg=len(str1)/n
print(avg)

14.145223633351739

In [57]:
n=len(df['original_title'])
n

10866

In [63]:
df2=df[(df['release_year']>=2000) & (df['release_year']<=2005)]

In [64]:
df2

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
2633,120,tt0120737,8.575419,93000000,871368364,The Lord of the Rings: The Fellowship of the Ring,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,http://www.lordoftherings.net/,Peter Jackson,One ring to rule them all,...,"Young hobbit Frodo Baggins, after inheriting a...",178,Adventure|Fantasy|Action,WingNut Films|New Line Cinema|The Saul Zaentz ...,12/18/01,6079,7.8,2001,1.145284e+08,1.073080e+09
2634,671,tt0241527,8.021423,125000000,976475550,Harry Potter and the Philosopher's Stone,Daniel Radcliffe|Rupert Grint|Emma Watson|John...,http://harrypotter.warnerbros.com/harrypottera...,Chris Columbus,Let the Magic Begin.,...,Harry Potter has lived under the stairs at his...,152,Adventure|Fantasy|Family,1492 Pictures|Warner Bros.|Heyday Films,11/16/01,4265,7.2,2001,1.539360e+08,1.202518e+09
2635,1018,tt0166924,4.436367,15000000,20117339,Mulholland Drive,Naomi Watts|Laura Harring|Ann Miller|Dan Heday...,NaN,David Lynch,An actress longing to be a star. A woman searc...,...,After a car wreck on the winding Mulholland Dr...,147,Thriller|Drama|Mystery,Asymmetrical Productions|Les Films Alain Sarde...,5/16/01,709,7.4,2001,1.847232e+07,2.477426e+07
2636,141,tt0246578,3.851009,6000000,1270522,Donnie Darko,Jake Gyllenhaal|Patrick Swayze|Drew Barrymore|...,NaN,Richard Kelly,Dark. Darker. Darko.,...,"After narrowly escaping a bizarre accident, a ...",113,Fantasy|Drama|Mystery,Pandora Cinema|Flower Films|Adam Fields Produc...,1/18/01,1777,7.5,2001,7.388929e+06,1.564633e+06
2637,585,tt0198781,3.204295,115000000,562816256,"Monsters, Inc.",John Goodman|Billy Crystal|Mary Gibbs|Steve Bu...,http://movies.disney.com/monsters-inc,Lee Unkrich|David Silverman|Pete Docter,We Scare Because We Care.,...,"James Sullivan and Mike Wazowski are monsters,...",92,Fantasy|Animation|Family|Comedy,Walt Disney Pictures|Pixar Animation Studios,11/1/01,3899,7.3,2001,1.416211e+08,6.931015e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8883,36047,tt0163676,0.015997,15000000,5217498,The In Crowd,Susan Ward|Lori Heuring|Matthew Settle|Nathan ...,http://in-crowd.warnerbros.com/,Mary Lambert,What would you do to get in?,...,A mentally disturbed young woman takes a job a...,105,Thriller,Warner Bros. Pictures,7/19/00,12,5.2,2000,1.899438e+07,6.606877e+06
8884,97351,tt0222270,0.006865,0,0,Phir Bhi Dil Hai Hindustani,Juhi Chawla|Shah Rukh Khan|Johnny Lever|Shakti...,NaN,Aziz Mirza,NaN,...,"Rival news-reporters, Ajay Bakshi (Shahrukh Kh...",168,Romance|Comedy|Drama,NaN,1/21/00,12,7.2,2000,0.000000e+00,0.000000e+00
8885,20438,tt0234853,0.005784,0,0,The Tao of Steve,Donal Logue|Ayelet Kaznelson|John Hines|John H...,NaN,Jenniphr Goodman,Why do women find this man irresistible?,...,"Underachieving, overweight kindergarten teache...",87,Comedy|Romance,Good Machine|Thunderhead Productions,8/4/00,13,5.5,2000,0.000000e+00,0.000000e+00
8886,18292,tt0262432,0.080819,0,0,George Washington,Candace Evanofski|Donald Holden|Damian Jewan L...,NaN,David Gordon Green,NaN,...,A delicately told and deceptively simple story...,89,Drama,NaN,10/1/00,14,4.9,2000,0.000000e+00,0.000000e+00
8887,44756,tt0250440,0.004010,0,0,Is It Fall Yet?,Tracy Grandstaff|Wendy Hoopes,NaN,Karen Disher|Guy Moore,NaN,...,Is It Fall Yet? continues the series' running ...,75,Animation|Comedy,NaN,8/27/00,14,7.3,2000,0.000000e+00,0.000000e+00

In [68]:
str1=''
n=len(df2['original_title'])
for i in df2['original_title']:
    str1=str1+i.replace(' ','')
avg1=len(str1)/n
print(avg1)

14.283935981031417

common Genre for vin Diesel movie

In [102]:
df1=df.dropna()
df1

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/15,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/15,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/15,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/15,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/15,2947,7.3,2015,1.747999e+08,1.385749e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10724,668,tt0064757,1.778746,7000000,81974493,On Her Majesty's Secret Service,George Lazenby|Diana Rigg|Telly Savalas|Gabrie...,http://www.mgm.com/view/movie/1411/On-Her-Maje...,Peter R. Hunt,Far up! Far out! Far more! James Bond 007 is b...,...,James Bond tracks archnemesis Ernst Blofeld to...,142,Adventure|Action|Thriller,Eon Productions|Metro-Goldwyn-Mayer (MGM)|Danjaq,12/12/69,258,6.4,1969,4.160985e+07,4.872780e+08
10759,948,tt0077651,1.198849,300000,70000000,Halloween,Donald Pleasence|Jamie Lee Curtis|P.J. Soles|N...,http://www.theofficialjohncarpenter.com/hallow...,John Carpenter,The Night HE Came Home!,...,"A psychotic murderer, institutionalized since ...",91,Horror|Thriller,Compass International Pictures|Falcon Internat...,10/25/78,522,7.3,1978,1.002810e+06,2.339890e+08
10760,8469,tt0077975,1.157930,2700000,141000000,Animal House,John Belushi|Tim Matheson|John Vernon|Verna Bl...,http://www.animalhouse.com/,John Landis,It was the Deltas against the rules... the rul...,...,"At a 1962 College, Dean Vernon Wormer is deter...",109,Comedy,Universal Pictures|Oregon Film Factory|Stage I...,7/27/78,230,6.7,1978,9.025292e+06,4.713208e+08
10817,13963,tt0077838,0.064029,0,321952,The Last Waltz,Robbie Robertson|Rick Danko|Levon Helm|Richard...,http://www.mgm.com/#/our-titles/1092/The-Last-...,Martin Scorsese,It Started as a Concert. It Became a Celebration.,...,Martin Scorsese's rockumentary intertwines foo...,117,Documentary|Music,FM Productions|Last Waltz Inc.,5/1/78,33,8.0,1978,0.000000e+00,1.076189e+06
10819,16214,tt0077696,0.044675,0,78000000,Hooper,Burt Reynolds|Robert Klein|Adam West|Jan-Micha...,http://en.wikipedia.org/wiki/Hooper_(film),Hal Needham,The greatest stuntman alive!,...,Burt Reynolds plays a legendary stunt man know...,107,Action|Comedy,Warner Bros.,7/28/78,13,6.0,1978,0.000000e+00,2.607307e+08

In [105]:
df2=df1[df1['cast'].str.contains('Vin Diesel')]

In [107]:
str2=''
for i in df2['genres']:
    str2+=i

In [112]:
k=str2.split('|')
genres_and_count={}
count=0
for j in k:
    try:
        count = genres_and_count[j]
        genres_and_count[j] = count + 1
    except:
        genres_and_count[j] = 1

In [118]:
max(genres_and_count,key=genres_and_count.get)

'Action'

In [116]:
genres_and_count

{'Action': 5,
 'Crime': 2,
 'ThrillerFantasy': 1,
 'AdventureAction': 2,
 'Science Fiction': 3,
 'Drama': 2,
 'ThrillerCrime': 1,
 'ThrillerAction': 3,
 'Adventure': 1,
 'Thriller': 3,
 'CrimeAction': 2,
 'DramaScience Fiction': 1,
 'Comedy': 1,
 'Family': 1,
 'ThrillerAdventure': 1,
 'Science FictionThriller': 1}

In [132]:
df4=df1[df1['cast'].str.contains('Emma Watson')]
str4=''
for i in df4['genres']:
    str4+=i
k=str4.split('|')
genres_and_count={}
count=0
for j in k:
    try:
        count = genres_and_count[j]
        genres_and_count[j] = count + 1
    except:
        genres_and_count[j] = 1

max(genres_and_count,key=genres_and_count.get)

'Fantasy'

In [131]:
genres_and_count

{'Drama': 1,
 'AdventureAdventure': 1,
 'Fantasy': 5,
 'FamilyAdventure': 4,
 'FamilyAnimation': 1,
 'Comedy': 1,
 'Family': 3,
 'FantasyDrama': 1,
 'RomanceAdventure': 1,
 'MysteryDrama': 1}

Movies with most and least earned revenue

In [134]:
df.columns

Index(['id', 'imdb_id', 'popularity', 'budget', 'revenue', 'original_title',
       'cast', 'homepage', 'director', 'tagline', 'keywords', 'overview',
       'runtime', 'genres', 'production_companies', 'release_date',
       'vote_count', 'vote_average', 'release_year', 'budget_adj',
       'revenue_adj'],
      dtype='object')

In [138]:
#most earned
df[df['revenue']==df['revenue'].max()][['original_title','revenue']]

     original_title     revenue
1386         Avatar  2781505847

In [161]:
df1=df.loc[df['revenue']!=0]
#df1=df[df['revenue']!=0]

In [162]:
df1[df1['revenue']==df1['revenue'].min()][['original_title','revenue']].head(1)

       original_title  revenue
5067  Shattered Glass        2

average runtime in year 2006

In [168]:
avg=df[df['release_year']==2006]['runtime'].mean()
avg

101.68382352941177